config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  
  root 'welcome#index'

  
  get 'public/index', to: 'public#index'
  get 'public/scss', to: 'public#scss'
  
  get 'member/index', to: 'member#index'

  namespace :public do
    
    get 'designs/vesco', to: 'designs#vesco'
    
    namespace :designs do
      get 'photo_sharing_app/index', to: 'photo_sharing_app#index'
      get 'photo_sharing_app/about', to: 'photo_sharing_app#about'
      get 'photo_sharing_app/contact', to: 'photo_sharing_app#contact'
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/member_controller.rb
class MemberController < ApplicationController
  
  def index
    
  end
  
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  
  skip_before_action :authenticate_user!
  
  #this will allow me to create the index view with it's own layout
  #layout false, only: :index
  
  def index
    
  end
  
  def scss
    
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  skip_before_action :authenticate_user!, only: [:index]
  
  def index
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def body_class
    [controller_name, action_name].join(' ')
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "JBL Projects" %></title>
    <%= csrf_meta_tags %>
    
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700" rel="stylesheet">
    
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="<%= body_class %>">
  
    <%= render '/shared/main_nav' %>

    <div class="container container-main">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

    <%= render '/shared/footer_nav' %>
    
  </body>
  <%= javascript_include_tag "bottom/bootstrap_submenu" %>
</html>

app/views/layouts/designs.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <%= content_for?(:meta_seo) ? yield(:meta_seo) : "" %>
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "JBL Ideas" %></title>
    <%= csrf_meta_tags %>
    
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700" rel="stylesheet">
    
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body class="<%= body_class %>" <%= content_for?(:data_attributes) ? yield(:data_attributes) : "" %>>
  
    <%= yield %>
    
  </body>
</html>

app/views/shared/_footer_nav.html.erb
<footer class="navbar-fixed-bottom navbar-inverse application-footer">
  <div class="container">
    &copy; Company 2017
  </div>
</footer>

app/views/shared/_main_nav.html.erb
<nav class="navbar navbar-inverse navbar-static-top application-nav" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "JBL Projects", root_path, class: 'navbar-brand'  %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">Public <i class="fa fa-caret-down"></i></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Home', public_index_path %></li>
            <li class="divider"></li>
            <li class="dropdown dropdown-submenu"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Design Templates</a>
              <ul class="dropdown-menu">
                <li><%= link_to "Vesco - The Modern Responsive Website", public_designs_vesco_path %></li>
                <li><%= link_to "Gamma - A Photo Sharing App", public_designs_photo_sharing_app_index_path %></li>
              </ul>
            </li>
          </ul>
        </li>
        <li><%= link_to "Members", member_index_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if @current_user %>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</nav>

app/views/welcome/index.html.erb
<h1>Welcome</h1>